hydra: 
  run:
    dir: runs/${MODEL_NAME}/model  #2022-03-22/13-15-31 #${now:%Y-%m-%d}/${now:%H-%M-%S}
  verbose: false
# can be NEW, LATEST, or a given checkpoint filename
MODEL_NAME: AS_2D_original #AS_golosov_para #AS_constrained_split #cont_vanilla
STARTING_POINT: NEW #Iter_27.pth
CHECKPOINT_INTERVAL: 1
WORKER_MAIN_LOG_LEVEL: ERROR
WORKER_TRAIN_LOG_LEVEL: INFO
num_cycles: 9000
seed: 0  
